/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BorrowedEquipmentResponse } from '../models/borrowed-equipment-response';
export interface PageResponseBorrowedEquipmentResponse {
  content?: Array<BorrowedEquipmentResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
