/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BorrowedEquipmentResponse } from './models/borrowed-equipment-response';
export type { EquipmentRequest } from './models/equipment-request';
export type { EquipmentResponse } from './models/equipment-response';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedbackResponse } from './models/feedback-response';
export type { PageResponseBorrowedEquipmentResponse } from './models/page-response-borrowed-equipment-response';
export type { PageResponseEquipmentResponse } from './models/page-response-equipment-response';
export type { PageResponseFeedbackResponse } from './models/page-response-feedback-response';
export type { RegistrationRequest } from './models/registration-request';
